### ISSUE TITLE
[FEAT] Allow CSS to style elements

### ISSUE THREAD

**Issue by sjregan** [roman-rr/cupertino-pane#114]
**What are you trying to add to Cupertino-Pane?**
Allow CSS to be used to set the design of the elements used to display the pane.

*Describe your feature request **detailed***
Currently there are inline styles hard-coded into the library, it would be useful to have only the necessary styles hard-coded and the rest defined via CSS.

eg. You cannot define the border radius via CSS.

**Is there an alternative at the latest version?**

[ ] Yes (descripe the alternative)
[ X] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[X ] No

**Comment by roman-rr** [comment]
Hello @sjregan Thank you for issue!
Some hardcoded parts of css exist, but you might be able to overwrite styles with css. 
Could you please try these ?
```css
.cupertino-pane-wrapper .pane {
  border-radius: 0 !important;
}
```

or for angular components 
```css
::ng-deep .cupertino-pane-wrapper .pane {
  border-radius: 0 !important;
}
```
