### ISSUE TITLE
Feature Width

### ISSUE THREAD

**Issue by danielehrhardt** [roman-rr/cupertino-pane#39]
Add a Feature to change the max width

**Comment by roman-rr** [comment]
@danielehrhardt have you try to change with css ? 

```css
::ng-deep .pane,
.pane {
  max-width: 1000px;
}
```
