### ISSUE TITLE
[Feature] Change css styles of pane elements 

### ISSUE THREAD

**Issue by Evanzsnr** [roman-rr/cupertino-pane#89]
**What are you trying to add to Cupertino-Pane?**
Hi, is it possible to change the border-radius or remove it completely?

*Describe your feature request **detailed***
I need to remove the border-radius and remove the top bar containing the showDraggable button at the top.

**Comment by roman-rr** [comment]
Hello @Evanzsnr 
You able to style elements directly with css
```css
.cupertino-pane-wrapper .pane {
  border-radius: none;
}
```

or for angular component:
```css
::ng-deep .cupertino-pane-wrapper .pane {
  border-radius: none;
}
```

**Comment by Evanzsnr** [comment]
@roman-rr I tried your solution but the styles couldn't be applied.

**Comment by Evanzsnr** [comment]
@roman-rr I applied the styles but they failed to work.

**Comment by roman-rr** [comment]
@Evanzsnr What you mean by "failed to work" ?

**Comment by roman-rr** [comment]
@Evanzsnr Checked once again, this works for border-radius: 

```css
.cupertino-pane-wrapper .pane {
  border-radius: 0 !important;
}
```
